<?php

/**
 * @file
 * Provide functionality to allow static site generation from the master branch
 */

/**
 * Implements hook_menu().
 */
function zariz_static_menu() {
  $items = array();

  $items['zariz-pages'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'zariz_static_get_pages_list_json',
    'access arguments' => array('access content'),
    'title' => 'Pages list',
    'description' => 'Get pages list by a single or multiple snapshots.'
  );

  return $items;
}


/**
 * Page callback; Return pages list by snapshot in JSON.
 *
 * @param Snapshot $snapshot
 *   The Snapshot entity.
 */
function zariz_static_get_pages_list_json($branch_id = NULL) {
  $branch_id = $branch_id ? $branch_id : variable_get('zariz_master_branch');
  if (!$branch_id) {
    // No branch ID.
    return;
  }

  // Get the latest snapshot of the branch.
  $snapshot = zariz_get_snapshot_from_branch($branch_id);
  drupal_json_output(zariz_get_page_list_by_snapshot($snapshot));
}

/**
 * Process HTML.
 *
 * Wrap CSS <link> tags with Grunt's usemin blocks.
 *
 * @todo: Get the <!--[if] and remote files outside of the usemin block
 */
function zariz_static_process_html(&$variables) {
  foreach ($variables['css'] as &$row) {
    $row['preprocess'] = FALSE;
  }

  $output = array();
  $output[] = '<!-- build:css(.tmp) styles/main.css -->';
  $output[] = drupal_get_css($variables['css']);
  $output[] = '<!-- endbuild -->';

  $styles = implode("\r\n", $output);

  // When calling drupal_get_css() it fires hook_css_alter(), so we need to
  // replace some styles using string replacements.
  $styles = str_replace(array('<style>', '</style>'), '', $styles);
  $styles = preg_replace_callback('/@import url\((.*)\);/i', 'zariz_static_replace_style_import', $styles);
  $variables['styles'] = $styles;
}

/**
 * Preg replace callback; Replace style tags with a <link> tag.
 */
function zariz_static_replace_style_import($matches) {
  return '<link type="text/css" rel="stylesheet" href=' . $matches[1] . ' media="all" />';
}
